### ISSUE TITLE
Client in ambiente Linux

### ISSUE THREAD

**Issue by ummone67** [MicrosoftDocs/SCCMDocs.it-it#2]
Sarebbe utile un upgrade del Client per Linux per supportare OpenSSL 1.1.0 che al momento non è supportato. 

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 22765ffe-cef8-a88f-5f71-00caf9b47046
* Version Independent ID: cb5ad492-39d1-f63d-0bd2-7f3a0b1d8af0
* Content: [Novità della versione 1806 - Configuration Manager](https://docs.microsoft.com/it-it/sccm/core/plan-design/changes/whats-new-in-version-1806)
* Content Source: [sccm/core/plan-design/changes/whats-new-in-version-1806.md](https://github.com/Microsoft/SCCMDocs.it-it/blob/live/sccm/core/plan-design/changes/whats-new-in-version-1806.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by CeciAc** [comment]
Salve, @ummone67 

Il tuo contributo è molto apprezzato. Il nostro team può rispondere solo a commenti e suggerimenti relativi alla documentazione. 
Inviare commenti e suggerimenti relativi ai prodotti tramite il pulsante "Commenti sul prodotto" nella parte inferiore della pagina DOCS. 

I commenti relativi alla documentazione possono invece essere inviati tramite questo canale. 
Il tuo contributo ai nostri articoli è molto apprezzato.  

Cordiali saluti, 
Il team internazionale Microsoft Docs
